/**
 * Ícones da aplicação.
 *
 * Este arquivo preserva os nomes já usados nas telas enquanto renderiza somente
 * componentes do Phosphor. Isso permite a transição global sem alterar a
 * semântica, acessibilidade ou os tamanhos definidos em cada componente.
 */
import type { Icon } from '@phosphor-icons/react';
import {
  ActivityIcon, ArrowCircleDownIcon, ArrowCircleUpIcon, ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon, ArrowDownIcon, ArrowLeftIcon, ArrowRightIcon,
  ArrowSquareOutIcon, ArrowUpIcon, ArrowsDownUpIcon, BankIcon, BellIcon, BriefcaseIcon,
  BuildingIcon, BuildingsIcon, CakeIcon, CalendarCheckIcon, CalendarIcon,
  CalendarPlusIcon, CalendarXIcon, CameraIcon, CaretDownIcon, CaretLeftIcon, CaretRightIcon,
  CaretUpIcon, ChartBarIcon, ChartPieSliceIcon, ChatCircleIcon, ChatTextIcon,
  CheckCircleIcon, CheckIcon, CircleIcon, ClockIcon, CoffeeIcon, CommandIcon,
  ConfettiIcon, CopyIcon, CreditCardIcon, CropIcon, CrownIcon, CurrencyDollarIcon,
  DeviceMobileIcon, DotIcon, DotsSixVerticalIcon, DotsThreeIcon,
  DotsThreeVerticalIcon, DownloadSimpleIcon, EnvelopeIcon, EyeIcon, EyeSlashIcon,
  FacebookLogoIcon, FileTextIcon, FileXlsIcon, FloppyDiskIcon, FunnelIcon,
  GearIcon, GiftIcon, GlobeIcon, HandshakeIcon, HeadphonesIcon, HeartIcon,
  HouseIcon, ImageIcon, InfoIcon, InstagramLogoIcon, KeyIcon, LightningIcon,
  LinkIcon, ListIcon, ListNumbersIcon, LockIcon, LockKeyIcon, MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon, MagnifyingGlassPlusIcon, MapPinIcon, MegaphoneIcon,
  MinusIcon, MoneyIcon, MoonIcon, NavigationArrowIcon, PackageIcon, PaletteIcon,
  PaperPlaneTiltIcon, PauseIcon, PencilIcon, PencilSimpleIcon,
  PercentIcon, PhoneIcon, PlayIcon, PlusIcon, PowerIcon, ProhibitIcon, QrCodeIcon,
  QuotesIcon, ReceiptIcon, RepeatIcon, ScissorsIcon, ScrollIcon, ShareNetworkIcon,
  ShieldCheckIcon, ShieldIcon, ShoppingCartIcon, SidebarSimpleIcon, SignOutIcon,
  SlidersHorizontalIcon, SparkleIcon, SpinnerIcon, SquaresFourIcon, StarIcon,
  StethoscopeIcon, SunIcon, TableIcon, TagIcon, TargetIcon, TicketIcon, TrashIcon,
  TreePalmIcon, TrendDownIcon, TrendUpIcon, TrophyIcon, UploadSimpleIcon, UserCheckIcon,
  UserCircleIcon, UserIcon, UserMinusIcon, UserPlusIcon, UsersIcon, UsersThreeIcon, WalletIcon,
  WarningCircleIcon, WarningIcon, WarehouseIcon, WifiHighIcon, XCircleIcon, XIcon,
} from '@phosphor-icons/react';

export type LucideIcon = Icon;

export {
  ActivityIcon as Activity,
  WarningCircleIcon as AlertCircle,
  WarningIcon as AlertTriangle,
  ArrowDownIcon as ArrowDown,
  ArrowCircleDownIcon as ArrowDownCircle,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowUpIcon as ArrowUp,
  ArrowCircleUpIcon as ArrowUpCircle,
  ArrowsDownUpIcon as ArrowUpDown,
  ProhibitIcon as Ban,
  MoneyIcon as Banknote,
  ChartBarIcon as BarChart3,
  BellIcon as Bell,
  BriefcaseIcon as Briefcase,
  BuildingIcon as Building,
  BuildingsIcon as Building2,
  CakeIcon as Cake,
  CalendarIcon as Calendar,
  CalendarCheckIcon as CalendarCheck,
  CalendarCheckIcon as CalendarCheck2,
  CalendarIcon as CalendarClock,
  CalendarIcon as CalendarDays,
  CalendarIcon,
  CalendarPlusIcon as CalendarPlus,
  CalendarXIcon as CalendarX,
  CameraIcon as Camera,
  CheckIcon as Check,
  CheckCircleIcon as CheckCircle,
  CheckCircleIcon as CheckCircle2,
  CaretDownIcon as ChevronDown,
  CaretLeftIcon as ChevronLeft,
  CaretRightIcon as ChevronRight,
  CaretUpIcon as ChevronUp,
  CircleIcon as Circle,
  ClockIcon as Clock,
  CoffeeIcon as Coffee,
  CommandIcon as Command,
  CopyIcon as Copy,
  CreditCardIcon as CreditCard,
  CropIcon as Crop,
  CrownIcon as Crown,
  CurrencyDollarIcon as DollarSign,
  DotIcon as Dot,
  DownloadSimpleIcon as Download,
  PencilSimpleIcon as Edit,
  ArrowSquareOutIcon as ExternalLink,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FacebookLogoIcon as Facebook,
  FileXlsIcon as FileSpreadsheet,
  FileTextIcon as FileText,
  FunnelIcon as Filter,
  GiftIcon as Gift,
  GlobeIcon as Globe,
  DotsSixVerticalIcon as GripVertical,
  HeadphonesIcon as Headphones,
  HeartIcon as Heart,
  HandshakeIcon as HeartHandshake,
  HouseIcon as Home,
  ImageIcon as Image,
  ImageIcon,
  InfoIcon as Info,
  InstagramLogoIcon as Instagram,
  KeyIcon as KeyRound,
  SquaresFourIcon as LayoutDashboard,
  LinkIcon as Link,
  ListNumbersIcon as ListOrdered,
  SpinnerIcon as Loader2,
  LockIcon as Lock,
  LockKeyIcon as LockKeyhole,
  SignOutIcon as LogOut,
  EnvelopeIcon as Mail,
  MapPinIcon as MapPin,
  MegaphoneIcon as Megaphone,
  ListIcon as Menu,
  ChatCircleIcon as MessageCircle,
  ChatTextIcon as MessageSquare,
  MinusIcon as Minus,
  MoonIcon as Moon,
  DotsThreeIcon as MoreHorizontal,
  DotsThreeVerticalIcon as MoreVertical,
  NavigationArrowIcon as Navigation,
  PackageIcon as Package,
  PaletteIcon as Palette,
  TreePalmIcon as Palmtree,
  SidebarSimpleIcon as PanelLeftClose,
  SidebarSimpleIcon as PanelLeftOpen,
  ConfettiIcon as PartyPopper,
  PauseIcon as Pause,
  PencilIcon as Pencil,
  PercentIcon as Percent,
  PhoneIcon as Phone,
  ChartPieSliceIcon as PieChart,
  PlayIcon as Play,
  PlusIcon as Plus,
  PowerIcon as Power,
  PowerIcon as PowerOff,
  QrCodeIcon as QrCode,
  QuotesIcon as Quote,
  ReceiptIcon as Receipt,
  ArrowClockwiseIcon as RefreshCw,
  RepeatIcon as Repeat,
  ArrowCounterClockwiseIcon as RotateCcw,
  ArrowClockwiseIcon as RotateCw,
  FloppyDiskIcon as Save,
  ScissorsIcon as Scissors,
  ScrollIcon as ScrollText,
  MagnifyingGlassIcon as Search,
  PaperPlaneTiltIcon as Send,
  GearIcon as Settings,
  ShareNetworkIcon as Share2,
  ShieldIcon as Shield,
  ShieldCheckIcon as ShieldCheck,
  ShoppingCartIcon as ShoppingCart,
  SlidersHorizontalIcon as SlidersHorizontal,
  DeviceMobileIcon as Smartphone,
  SparkleIcon as Sparkles,
  StarIcon as Star,
  StethoscopeIcon as Stethoscope,
  SunIcon as Sun,
  TableIcon as Table2,
  TagIcon as Tag,
  TargetIcon as Target,
  TicketIcon as Ticket,
  TrashIcon as Trash2,
  TrendDownIcon as TrendingDown,
  TrendUpIcon as TrendingUp,
  TrophyIcon as Trophy,
  UploadSimpleIcon as Upload,
  UserIcon as User,
  UserCheckIcon as UserCheck,
  UserCircleIcon as UserCircle,
  UserPlusIcon as UserPlus,
  UserIcon as UserRound,
  UserMinusIcon as UserX,
  UsersIcon as Users,
  UsersThreeIcon as UsersRound,
  WalletIcon as Wallet,
  WarehouseIcon as Warehouse,
  WifiHighIcon as Wifi,
  XIcon as X,
  XCircleIcon as XCircle,
  LightningIcon as Zap,
  MagnifyingGlassPlusIcon as ZoomIn,
  MagnifyingGlassMinusIcon as ZoomOut,
};
